### PR TITLE
Website upgrade refactor

### LINKED ISSUE #11: Update fetching location of "CIPM Recommendations"
From Janet Miles of the BIPM:

> Most (if not all) of the CIPM Recommendations have been entered into the website, but unfortunately the problems with their display have not yet been resolved (for example, you will see "Resolution" even where it should be "Recommendation"). 

i.e. These are Recommendations, not Resolutions.

They should all be available here: https://www.bipm.org/en/committees/ci/cipm/recommendations

Data locations:

e.g. 
The 1948 Resolution at https://www.bipm.org/en/committees/ci/cipm/42-1948/resolution-
The 1946 Resolutions at:
* https://www.bipm.org/en/committees/ci/cipm/41-1946/resolution-2 and
* https://www.bipm.org/en/committees/ci/cipm/41-1946/resolution-1.

> All the links include "resolution" regardless of whether the text was a "resolution" or "recommendation".
In the software we have to differentiate.

> It might however be helpful to the user to retain the page information (e.g.  CIPM, 1948, p88).

We need to retain the page information.

We also need to provide this URL in the data structure.

### LINKED ISSUE #12: Update fetching location of "CIPM Decisions"
All "CIPM Decisions" are available from this page now:
https://www.bipm.org/en/committees/ci/cipm/outcomes

We also need to support the "Topic" tag per Decision.
Screenshot 2022-01-14 at 2 16 53 PM

### LINKED ISSUE #13: Update fetching location of "CGPM Resolutions"
All located here: 
https://www.bipm.org/en/committees/cg/cgpm/cgpm-resolutions

Individual pages look like this:
https://www.bipm.org/en/committees/cg/cgpm/1-1889/resolution-

We need to keep all information of the page, including the PDF link, the page number, date of meeting, etc.

### LINKED ISSUE #14: Update fetching location of CIPM meetings
All available here: https://www.bipm.org/en/committees/ci/cipm/meetings

We need to link the CIPM meetings to the CIPM Decisions and CIPM Recommendations too.

### PR DESCRIPTION
**Pull request by webdev778**
- Update fetching location of CIPM meetings Fix #14
- Update fetching location of "CGPM Resolutions"  Fix #13
- Update fetching location of "CIPM Decisions" Fix #12 
- Update fetching location of "CIPM Recommendations" Fix #11

### CODE REVIEW

**Comment by ronaldtse** [comment]
Ruby 2.5 is failing -- @CAMOBAP can we remove it since it is already EOL? Thanks!

**Comment by ronaldtse** [comment]
@webdev778 the build is failing on macOS and Windows because of:

```
  Your bundle only supports platforms ["x86_64-linux"] but your local platform is
  x86_64-darwin-19. Add the current platform to the lockfile with `bundle lock
  --add-platform x86_64-darwin-19` and try again.
```

You can just remove Gemfile.lock.

**Comment by ronaldtse** [comment]
@webdev778 we also want to move all the data to the https://github.com/metanorma/bipm-data-outcomes repository, and remove all the data from this current repository.

**Comment by webdev778** [comment]
> @webdev778 we also want to move all the data to the https://github.com/metanorma/bipm-data-outcomes repository, and remove all the data from this current repository.

Fixed with PR #17

**Comment by ronaldtse** [comment]
Thanks @webdev778 !

**Pull request merged**
